name: Publish

on: 
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubunto-latest

  steps:
    -uses: actions/checkout@v3
    
    -name: setup .Net
    uses: actions/setup-dotnet@v3
    width:
    dotnet-version: '6.0.x'
    
    -name: Restore
    run: dotnet restore ./Aurora_be.sln

    -name: Build
    run: dotnet build ./Aurora_be.sln --configuration Release --no-restore

    -name: Publish
    run: dotnet publish ./Aurora_be.sln --configuration Release --no-build
    
    
